# Generated by Django 3.1.1 on 2021-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlform',
            name='PhoneNum',
            field=models.CharField(max_length=10),
        ),
    ]
